import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as React from "react";
import { Header } from "../components/templates/header";
import Grid from "@mui/material/Grid";
import { Select, Box, ThemeProvider } from "@mui/material";
import { ThemeSelector } from "../components/organism/theme-selector";
import { polarTheme, summerTheme } from "../styles/theme";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={polarTheme}>
        <main>
          <Box
            sx={{ flexGrow: 1 }}
            justifyContent="center"
            alignItems={"center"}
          >
            <Grid container>
              <Grid item xs={10}>
                <Grid container spacing={2} style={{ margin: 50 }}>
                  <Header
                    disableCustomTheme={true}
                    content={"I am a Pikachu header without Custom Theme"}
                  ></Header>
                  <Header
                    content={"I am a Pikachu header with Custom Theme"}
                  ></Header>
                </Grid>
                <Grid item xs={6} md={8}>
                  <div
                    style={{
                      position: "absolute",
                      bottom: 50,
                      paddingLeft: 50,
                    }}
                  >
                    It's a Multi-theme, token base, and atomic design nextJS
                    template for scalable development <b>by</b>{" "}
                    <a href="">@RogerMachado</a>
                  </div>
                </Grid>
              </Grid>
              <Grid
                item
                xs={2}
                style={{ backgroundColor: "#fff", paddingLeft: 15, width: 250 }}
              >
                <ThemeSelector />
              </Grid>
            </Grid>
          </Box>
        </main>
      </ThemeProvider>
    </>
  );
};

export default Home;
